name: Deploy to cPanel FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Build Project
        run: |
          npm run build
          cp package.json dist/package.json
          cp .env.example dist/.env.example

      - name: Deploy Node Passenger application over SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: "51.79.17.60"
          username: "gldlgarl"
          password: "p.Y30c8Y(KdgM3"
          port: 1624
          sftp_only: true
          local_path: "./dist/*"
          remote_path: "whisper"
          sftpArgs: "-o ConnectTimeout=15 -o StrictHostKeyChecking=no"

      - name: Deploy .htaccess separately
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: "51.79.17.60"
          username: "gldlgarl"
          password: "p.Y30c8Y(KdgM3"
          port: 1624
          sftp_only: true
          local_path: "./dist/.htaccess"
          remote_path: "whisper"
          sftpArgs: "-o ConnectTimeout=15 -o StrictHostKeyChecking=no"
